name: Linting and Checking of Infrastructure Code

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    terraform_code_checking:
        runs-on: ubuntu-latest
        name: Check Terraform Code Formatting
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - name: Checkout Project
              uses: actions/checkout@v3
              with:
                ref: ${{ github.ref }}
            - name: Setup Terraform
              uses:  hashicorp/setup-terraform@v2
              with:
                    terraform_version: 1.4.4
                    terraform_wrapper: false
            - name: Check if Terraform Code is properly formatted
              run: |
                terraform fmt -recursive -check | 
                while IFS= read -r string; do
                    echo "::warning file=./$string::is not formatted correctly"
                done
            - name: Terraform Init
              run: terraform init
            - name: Terraform Validate
              run: terraform validate
            - name: TfLint
              run: |
                curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
                tflint --recursive
              